version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.6
  working_directory: ~/marquez_python


jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: pip install --user  -r requirements.txt

  test:
    <<: *defaults
    steps:
      - checkout
      - run: pip install --user  -r test-requirements.txt
      - run: python -m pytest ./test

  release:
    <<: *defaults
    working_directory: ~/marquez_python
    environment:
      TWINE_USERNAME: ashulman
      TWINE_PASSWORD: TM99bdx9!xyz
    steps:
      - checkout
      - run: pip install --user twine
      - run: pip freeze
      - run: python setup.py sdist
      - run: echo $PATH
      - run: env
      - run: python -m twine upload --verbose dist/*

workflows:
  version: 2
  marquez_python:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          requires:
            - test
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}$/
            branches:
              only: master
